version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    # command: php artisan serve --host=0.0.0.0 --port=80
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
